name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['12.x', '14.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install deps and build (with cache)
        run: yarn install --frozen-lockfile --silent

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Upload coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: npx nyc report --reporter=text-lcov | npx codecov --disable=gcov --pipe

      - name: Build
        run: yarn build:prod
